### ISSUE TITLE
The devicehub server does not start

### ISSUE THREAD

**Issue by raknamber1** [VKCOM/devicehub#3]
Hi,

When unfolding according to this instruction https://github.com/VKCOM/devicehub/blob/master/doc/docker-compose-deployment.md

Everything seems to be going well, except that https://github.com/VKCOM/devicehub/blob/master/Dockerfile I had to fix it a little.

But I'm facing a problem.

```
2024-05-21T14:25:51.193Z INF/app 61 [*] Using pre-built resources
/app/node_modules/yargs/yargs.js:1078
      else throw err
           ^

Error: Cannot parse config file: '/app/lib/units/api/config/default.yaml': TypeError: VisionmediaYaml.eval is not a function
    at Config.util.parseFile (/app/node_modules/config/lib/config.js:963:11)
    at /app/node_modules/config/lib/config.js:725:28
    at Array.forEach (<anonymous>)
    at /app/node_modules/config/lib/config.js:721:14
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/app/node_modules/config/lib/config.js:720:13)
    at new Config (/app/node_modules/config/lib/config.js:136:27)
    at Object.<anonymous> (/app/node_modules/config/lib/config.js:1797:31)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at new Runner (/app/node_modules/swagger-node-runner/index.js:166:16)
    at Object.create (/app/node_modules/swagger-node-runner/index.js:57:3)

Node.js v17.9.0
```

Please tell me how can this be solved?

**Comment by DaniilSmirnov** [comment]
Hi, issue fixed in https://github.com/VKCOM/devicehub/pull/4

**Comment by raknamber1** [comment]
And when starting docker-compose, an error is returned:

```
5.153 npm notice New major version of npm available! 8.5.5 -> 10.8.0
5.153 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.8.0>
5.153 npm notice Run `npm install -g npm@10.8.0` to update!
5.153 npm notice 
5.155 npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

Added `npm install` to https://github.com/VKCOM/devicehub/blob/master/Dockerfile#L52 and so it worked, you can probably include it in some kind of PR too

**Comment by romezz** [comment]
@DaniilSmirnov wouldn’t it be superfluous to remove `image: devicehub`  from docker-compose.yaml

**Comment by raknamber1** [comment]
@DaniilSmirnov wouldn’t it be superfluous to remove `image: devicehub`  from docker-compose.yaml?

**Comment by raknamber1** [comment]
@DaniilSmirnov Hi, 

I'm still facing a problem:

```
2024-05-24T07:03:49.937Z INF/util:procutil 1 [*] Forking "/app/lib/cli migrate"
/app/node_modules/yargs/yargs.js:1078
      else throw err
           ^

Error: Cannot find module 'rethinkdb'
Require stack:
- /app/lib/db/tables.js
- /app/lib/db/setup.js
- /app/lib/db/index.js
- /app/lib/cli/migrate/index.js
- /app/lib/cli/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/lib/db/tables.js:5:11)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/lib/db/setup.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/lib/db/tables.js',
    '/app/lib/db/setup.js',
    '/app/lib/db/index.js',
    '/app/lib/cli/migrate/index.js',
    '/app/lib/cli/index.js'
  ]
}

Node.js v17.9.0

/app/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 1
}

Node.js v17.9.0
2024-05-24T07:04:03.054Z INF/util:procutil 1 [*] Forking "/app/lib/cli migrate"
/app/node_modules/yargs/yargs.js:1078
      else throw err
           ^

Error: Cannot find module 'rethinkdb'
Require stack:
- /app/lib/db/tables.js
- /app/lib/db/setup.js
- /app/lib/db/index.js
- /app/lib/cli/migrate/index.js
- /app/lib/cli/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/lib/db/tables.js:5:11)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/lib/db/setup.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/lib/db/tables.js',
    '/app/lib/db/setup.js',
    '/app/lib/db/index.js',
    '/app/lib/cli/migrate/index.js',
    '/app/lib/cli/index.js'
  ]
}

Node.js v17.9.0

/app/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
ExitError: Exit code "1"
    at ChildProcess.<anonymous> (/app/lib/util/procutil.js:49:23)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 1
}

Node.js v17.9.0
```

**Comment by DaniilSmirnov** [comment]
You need to use --build-always option to rebuild devicehub image
